=== haleyga/fixinator/docs/specs/5.0_sp1/FIXRepository50SP1/Categories.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="dataroot">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Categories" maxOccurs="unbounded"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="Volume">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="6"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:element>
   <xs:element name="Section">
      <xs:simpleType>
         <xs:restriction base="xs:string"/>
      </xs:simpleType>
   </xs:element>
   <xs:element name="NotReqXML" type="xs:byte"/>
   <xs:element name="IncludeFile">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:enumeration value="components"/>
            <xs:enumeration value="fields"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:element>
   <xs:element name="GenerateImplFile" type="xs:boolean"/>
   <xs:element name="FIXMLFileName">
      <xs:simpleType>
         <xs:restriction base="xs:string"/>
      </xs:simpleType>
   </xs:element>
   <xs:element name="ComponentType">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:enumeration value="Field"/>
            <xs:enumeration value="Message"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:element>
   <xs:element name="Category">
      <xs:simpleType>
         <xs:restriction base="xs:string"/>
      </xs:simpleType>
   </xs:element>
   <xs:element name="Categories">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Category"/>
            <xs:element ref="FIXMLFileName"/>
            <xs:element ref="NotReqXML"/>
            <xs:element ref="GenerateImplFile"/>
            <xs:element ref="ComponentType"/>
            <xs:element ref="Section" minOccurs="0"/>
            <xs:element ref="Volume"/>
            <xs:element ref="IncludeFile" minOccurs="0"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== haleyga/fixinator/docs/specs/5.0_sp1/FIXRepository50SP1/Categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="categories.xsd">
   <Categories>
      <Category>Session</Category>
      <FIXMLFileName>session</FIXMLFileName>
      <NotReqXML>1</NotReqXML>
      <GenerateImplFile>false</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>session</Section>
      <Volume>2</Volume>
   </Categories>
   <Categories>
      <Category>Indication</Category>
      <FIXMLFileName>indications</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>pretrade</Section>
      <Volume>3</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>SingleGeneralOrderHandling</Category>
      <FIXMLFileName>order</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>trade</Section>
      <Volume>4</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>EventCommunication</Category>
      <FIXMLFileName>newsevents</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>pretrade</Section>
      <Volume>3</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>ProgramTrading</Category>
      <FIXMLFileName>listorders</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>trade</Section>
      <Volume>4</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>OrderMassHandling</Category>
      <FIXMLFileName>ordermasshandling</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>trade</Section>
      <Volume>4</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>Allocation</Category>
      <FIXMLFileName>allocation</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>posttrade</Section>
      <Volume>5</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>QuotationNegotiation</Category>
      <FIXMLFileName>quotation</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>pretrade</Section>
      <Volume>3</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>SettlementInstruction</Category>
      <FIXMLFileName>settlement</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>posttrade</Section>
      <Volume>5</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>MarketData</Category>
      <FIXMLFileName>marketdata</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>pretrade</Section>
      <Volume>3</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>MarketStructure</Category>
      <FIXMLFileName>marketstructure</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>pretrade</Section>
      <Volume>3</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>ReferenceData</Category>
      <FIXMLFileName>referencedata</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>pretrade</Section>
      <Volume>3</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>Common</Category>
      <FIXMLFileName>components</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Volume>1</Volume>
      <IncludeFile>fields</IncludeFile>
   </Categories>
   <Categories>
      <Category>RegistrationInstruction</Category>
      <FIXMLFileName>registration</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>posttrade</Section>
      <Volume>3</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>CrossOrders</Category>
      <FIXMLFileName>crossorders</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>trade</Section>
      <Volume>4</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>MultilegOrders</Category>
      <FIXMLFileName>multilegorders</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>trade</Section>
      <Volume>4</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>TradeCapture</Category>
      <FIXMLFileName>tradecapture</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>posttrade</Section>
      <Volume>5</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>Confirmation</Category>
      <FIXMLFileName>confirmation</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>posttrade</Section>
      <Volume>5</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>PositionMaintenance</Category>
      <FIXMLFileName>positions</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>posttrade</Section>
      <Volume>5</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>CollateralManagement</Category>
      <FIXMLFileName>collateral</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>posttrade</Section>
      <Volume>5</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>Application</Category>
      <FIXMLFileName>application</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>infrastructure</Section>
      <Volume>1</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>BusinessReject</Category>
      <FIXMLFileName>businessreject</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>infrastructure</Section>
      <Volume>1</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>Network</Category>
      <FIXMLFileName>network</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>infrastructure</Section>
      <Volume>1</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>UserManagement</Category>
      <FIXMLFileName>usermanagement</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>true</GenerateImplFile>
      <ComponentType>Message</ComponentType>
      <Section>infrastructure</Section>
      <Volume>1</Volume>
      <IncludeFile>components</IncludeFile>
   </Categories>
   <Categories>
      <Category>Fields</Category>
      <FIXMLFileName>fields</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>false</GenerateImplFile>
      <ComponentType>Field</ComponentType>
      <Volume>6</Volume>
   </Categories>
   <Categories>
      <Category>Impl Fields</Category>
      <FIXMLFileName>fields</FIXMLFileName>
      <NotReqXML>0</NotReqXML>
      <GenerateImplFile>false</GenerateImplFile>
      <ComponentType>Field</ComponentType>
      <Volume>6</Volume>
   </Categories>
</dataroot>
